Sanitize sys.version output
Apparently some versions of Python on some platforms add a new-line
character inside the version string which breaks HTTP headers:

   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/http/client.py", line 1263, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'tcms-api/12.8.2/Python 3.9.18 (main, Aug 28 2023, 08:38:32) \n[GCC 11.4.0]'